### ISSUE TITLE
Does not work with C++20, only C++17

### ISSUE THREAD

**Issue by Adam777Z** [robmikh/ScreenshotSample#5]
The sample does not work with C++20, it only works with C++17.

It would be good to have it working with C++20.

**Comment by robmikh** [comment]
Thanks for flagging this! I finally got around to porting the sample to C++20. The main issue was my use of `std::future` as a replacement for `IAsyncOperation` for non-WinRT types. 

As it turns out, using `std::future` this way is actually fairly sloppy, and burns a thread each time one is awaited in a coroutine. You can read more about that here: https://devblogs.microsoft.com/oldnewthing/20230217-00/?p=107842 . This sort of worked in C++17 (I believe C++/WinRT is also at play here), but stopped working in C++20.

The solution was to use a different type, and luckily the WIL library contains `wil::task` in the coroutine header.

You can find the change here: aae3b63c7b81106af5b616c21fb4e9ffaafe8b7a
